### ISSUE TITLE
Missing introducer/introducerSite for nodes

### ISSUE THREAD

**Issue by koliyo** [hylo-lang/hylo#1025]
Useful eg for LSP semantic tokens, see #1010

**Comment by koliyo** [comment]
Same for `conformance` and `extension`

**Comment by koliyo** [comment]
Also missing from `if`, `else`, `where`, etc?

Here is a workaround for some keyworks where I know the keyword is at the start of the range, and can not be prefixed eg by member access.

```swift

func keywordSite(_ site: SourceRange, len: Int) -> SourceRange {
  let start = site.start
  let end: SourceFile.Index = site.file.text.index(start, offsetBy: len)
  let indices = start..<end
  return SourceRange(indices, in: site.file)
}

extension SourceRepresentable where Part == WhereClause {
  public var introducerSite: SourceRange {
    keywordSite(site, len: 5)
  }
}

extension WhileStmt {
  public var introducerSite: SourceRange {
    keywordSite(site, len: 5)
  }
}


extension ReturnStmt {
  public var introducerSite: SourceRange {
    keywordSite(site, len: 6)
  }
}

extension ConditionalStmt {
  public var introducerSite: SourceRange {
    keywordSite(site, len: 2)
  }
}
```

**Comment by kyouko-taiga** [comment]
Thanks for opening this issue. It should be fairly simple to implement if anyone interested in parsing wants to give it a try. Otherwise I'll try to implement it during this week.

**Comment by koliyo** [comment]
Actually, I can take a stab at this! I wanna get more familiar with the hylo codebase, and as you say, this looks fairly straight forward.

Another comment is that there is a bit of inconsistency, some places there is

```swift
  public let introducer: SourceRepresentable<Introducer>
```
and others:

```swift
  public let introducerSite: SourceRange
```

Is there a specific reason for this, or just happened to end up like this?
