### ISSUE TITLE
Support conditional compilation

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#1035]
It should be possible to compile different code depending on the target. For example:

```
public fun main() {
#if os(macOS)
  print("Apple")
#elseif os(Linux)
  print("Pear")
#endif
}
```

See https://docs.swift.org/swift-book/documentation/the-swift-programming-language/statements/#Conditional-Compilation-Block for a list of the predicates we may want to support.

Note: this feature is probably necessary to write good `[U]Int` tests.

**Comment by lucteo** [comment]
Implemented with #1105, #1108, #1109, #1140
