### ISSUE TITLE
Remove requirement implementations from overload

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#1051]
Consider the following program:
```
public fun main() {
  let x: UInt = 1
  _ = x.infix+(1)
}
```
Currently, the call to `x.infix+` is building an overload set with the declarations of `AdditiveArithmetic.infix+` and `Uint.infix+`. That is inefficient because type inference has already determined that `UInt : AdditiveArithmetic`, meaning that can already decide the outcome of overload resolution before invoking the solver.

Reducing the size of overload sets while checking numerical expression is crucial to avoid combinatorial explosion, especially in the presence of literals.

**Comment by dabrahams** [comment]
I would say that `UInt.infix+` is more-specific than the other one, and if we got into a situation where they meant different things (I can easily imagine that with a different type), I would expect `UInt.infix+` to be called in this non-generic context.

**Comment by kyouko-taiga** [comment]
> I would say that `UInt.infix+` is more-specific than the other one

The current implementation of the overload solver would agree.

This issue is about removing `AdditiveArithmetic.infix+` before solving the overload set when we know that the solver will always pick `UInt.infix+` anyway. In other words, the goal is to prune the search tree early. Another tool we can (and do) use is to weight the choices of an overload set differently. But that only informs the heuristic guiding the search without guaranteed efficiency benefits.

>  if we got into a situation where they meant different things (I can easily imagine that with a different type), I would expect `UInt.infix+` to be called in this non-generic context

Not sure to understand. Are you thinking about this situation?

```
public trait P {
  fun f() -> Int
}
public trait Q {
  fun f() -> Int
}
type A: P, Q, Regular {
  public fun f() -> Int { 0 }
  public memberwise init
}

public fun main() {
  _ = A().f()
}
```
