### ISSUE TITLE
Broken type inference at binding initialization

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#1098]
This program should compile:
```
public fun main() {
  let x: Optional<Int> = Int.zero() // error: incompatible types 'Int' and 'Optional<Int>'
  if let y: Int = x { print(y) }
}
```
Surprisingly, replacing `Int.zero()` by a literal works as expected.

**Comment by peter-evans** [comment]
The program now compiles without error on the [latest version](https://github.com/hylo-lang/hylo/commit/ed677cb4dfa41d7a4b5fb4421207b51c92369c53) of the compiler. Perhaps this is fixed and can be closed?

**Comment by kyouko-taiga** [comment]
Indeed. I'm not sure that we should implicitly widen to union types at first initialization but that's another story.

Thanks @peter-evans
