### ISSUE TITLE
Build Error TargetMachine.h

### ISSUE THREAD

**Issue by tw-ilson** [hylo-lang/hylo#1119]
Hi, 
I am trying to build the compiler on linux. It failed with the message
`hylo/.build/checkouts/Swifty-LLVM/Sources/llvmshims/src/shim.cc:1:10: fatal error: 'llvm-c/TargetMachine.h' file not found`

Ok, so I tried on Darwin. 
also failed with the same message.

**Comment by dabrahams** [comment]
You have most likely not followed the instructions regarding the `llvm.pc` file in the README.

**Comment by kyouko-taiga** [comment]
I'm closing as the problem appears to have been fixed. Feel free to re-open if necessary.

**Comment by koliyo** [comment]
One caveat to this is that if llvm is updated by package manager, eg apt or homebrew, this needs to be done again. At least if using the installation of `llvm.pc` file instead of using environment variable.

**Comment by kyouko-taiga** [comment]
Well, it depends on what your update is doing to your system and how your `pc` file has been configured.

If you only use paths that do not mention a specific version of LLVM, I would expect that an "update" would work just fine as long as LLVM API doesn't change (but then I guess there's nothing we can do about it).

If you use paths mentioning a specific version _and_ you have a package manager able to host multiple versions of LLVM on your system, you should also be fine.

**Comment by dabrahams** [comment]
Expectations aside, it is a fact that I have had to regenerate my .pc files several times for this reason. 

I think we should tell people it might happen to them. Not everyone knows how this stuff works.

**Comment by koliyo** [comment]
Yes, at least for those using homebrew this is an issue. I have had to redo this setup several times. Eg my current `llvm.pc` file looks like this:
```
Name: LLVM
Description: Low-level Virtual Machine compiler framework
Version: 17.0.3
URL: http://www.llvm.org/
Libs: -L/opt/homebrew/Cellar/llvm/17.0.3/lib -L/opt/homebrew/Cellar/zstd/1.5.5/lib -lc++ -lLLVM-17
Cflags: -I/opt/homebrew/Cellar/llvm/17.0.3/include
```

And now after `brew upgrade` I have llvm 17.0.5

It should be possible to setup a `llvm.pc` with persistent paths, using the provided homebrew version symlinks, but this would require a modified setup compared to what is described in readme.

```
ls -l /opt/homebrew/opt/llvm
lrwxr-xr-x@ 1 nils  admin  21 Nov 17 08:55 /opt/homebrew/opt/llvm@ -> ../Cellar/llvm/17.0.5
```

Using the `/opt/homebrew/opt/llvm` symlink in the `llvm.pc` would be useful for homebrew.

**Comment by koliyo** [comment]
Yup this `llvm.pc` seem to work for me, the `Version` field is not up-to-date, but does not seem to be used by the compilation.

```
Name: LLVM
Description: Low-level Virtual Machine compiler framework
Version: 17.0.3
URL: http://www.llvm.org/
Libs: -L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/zstd/lib -lc++ -lLLVM-17
Cflags: -I/opt/homebrew/opt/llvm/include
```

**Comment by kyouko-taiga** [comment]
I sympathize with the difficulty to set things up but things are getting beyond our control I think. We didn't choose how SPM uses pkg-config files and we didn't choose how homebrew decides to store its packages. Similarly we can't tell where people decided to install clang and that might have a impact when they move things around.

We can certainly better document how these tools work and/or point to their docs but there will always be some level of customization we can't foresee because everyone can setup their system differently.
