### ISSUE TITLE
Undefined Behavior

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#1162]
To reproduce, do this repeatedly and you will observe crashes and other nasal demons.

- In TypedProgram.swift, around line 60 something, remove let isTypeCheckingParallel = isTypeCheckingParallel && false
- Build for macOS in debug mode
- Compile some non-empty program (e.g., Geometry.hylo from our test suite) with --typecheck

Replacing the use of a `Dispatch` queue with a semaphore does not suppress the issue.

The original text of this issue is below:

---------------
We have a seemingly random failure in CI happening on macOS in debug mode. I _think_ here is the first occurrence: https://github.com/hylo-lang/hylo/actions/runs/6909351716/job/18800508667

I merged this PR because re-running the CI job passed. So I think I had just observed a cosmic bug like the ones that sometimes happen on Windows. But since then we've been observing more consistent failures, always on macOS in debug mode:
- https://github.com/hylo-lang/hylo/actions/runs/6936813952/job/18869693667
- https://github.com/hylo-lang/hylo/actions/runs/6954943177/job/18979251777
- https://github.com/hylo-lang/hylo/actions/runs/6967854155/job/18960557859
- https://github.com/hylo-lang/hylo/actions/runs/6971167030/job/18970599927
- https://github.com/hylo-lang/hylo/actions/runs/6973308191/job/18978898066

@lucteo recently surfaced what's likely a data race (see https://github.com/hylo-lang/hylo/actions/runs/6973902095/job/18978712899) and I wonder if we're not observing the same problem, just at a smaller scale. To confirm I have disabled parallel type checking on a PR and tests passed on the first run (see https://github.com/hylo-lang/hylo/actions/runs/6977697662).

We should investigate this issue more thoroughly.

**Comment by kyouko-taiga** [comment]
Further evidence of a data race: https://github.com/hylo-lang/hylo/pull/1161/commits/ece4a3bc247dab0edcaf65fb18946c925265aab7

Rather than completely disabling parallel type checking, this patch only disables updates of the shared cache while the concurrent type checkers are running.

**Comment by dabrahams** [comment]
Do we think this is a bug in `Dispatch`?  Surely it can't be in my code! ;-)

**Comment by dabrahams** [comment]
I guess another possibility is that it's not a data race but a logical one because different computations of the "same" value in the cache are producing different results. Do we have an assertion checking for that?

**Comment by kyouko-taiga** [comment]
We discussed it with @lucteo yesterday and concluded that we needed your lights. The source of the problem might be here: https://github.com/hylo-lang/hylo/blob/8bf17efac9a11722b29899726b9f4c0b42b95861/Sources/Utils/SharedMutable.swift#L20-L32

@lucteo suspects that it is possible to get the shared value using the subscript and then cause a race when `modify(applying:)` is called. I'm skeptical because I think Swift should guarantee exclusive access to the CoW data structures that we got from the `get` subscript but maybe I'm overly confident in the safety guarantee we get in a concurrent context.

**Comment by kyouko-taiga** [comment]
> I guess another possibility is that it's not a data race but a logical one because different computations of the "same" value in the cache are producing different results. Do we have an assertion checking for that?

Yes, we have assertions for every update. That is the point of my `Monotonic` protocol. I would be surprised if the bug was due to an inconsistent update, but we never now. I'll double-check.

**Comment by dabrahams** [comment]
> suspects that it is possible to get the shared value using the subscript and then cause a race when modify(applying:) is called.

Any mutable state shared across threads is subject to logical races if used incorrectly, but there's clearly no data race in this code.  `mutex` is a dispatch queue and every access to the state is synchronized.  Getting the value with with the subscript copies the value.  You might look for uses of the subscript for read-modify-write (perhaps just remove the `set`ter) and make sure those uses use `modify`.  Any writes during the "modify" part of a r-m-w using the subscript will be discarded.  It's also going to be very inefficient if the shared value is a large CoW structure.  In fact that's likely enough that perhaps I have created an efficiency pitfall by allowing any access at all via subscript.  The user should be encouraged to do all reads of the stored value entirely inside a call just like `modify` (except without mutation).  But even if you fell into that efficiency trap, if your code is truly monotonic it should never have racy semantics.

**Comment by dabrahams** [comment]
Note that if we get rid of the subscript and never let the shared value escape from a `modify` (or corresponding read) accessor it would also eliminate any possibility of a data race due to a buggy CoW implementation.  I don't believe such a bug exists, but as you're ruling out causes it might be helpful to know that.

**Comment by kyouko-taiga** [comment]
> Any mutable state shared across threads is subject to logical races if used incorrectly

Am I correct to assume that even if we had a logical race, it could not possibly create undefined behavior?

That's what I think we've observed here. We have bus errors coming out of different places every time we run the compiler and it seems like the call stack gets corrupted.

**Comment by kyouko-taiga** [comment]
> Note that if we get rid of the subscript and never let the shared value escape from a modify (or corresponding read) accessor it would also eliminate any possibility of a data race due to a buggy CoW implementation. I don't believe such a bug exists, but as you're ruling out causes it might be helpful to know that.

Completely encapsulating read access to the contents of the shared value seems difficult to implement just to test an unlikely bug. The type checkers need to copy parts out a `modify` (or corresponding `read`) and use these values to run their logic.

For information, our code has roughly this pattern:
```
struct Cache {
  var local: TypedProgram
  var shared: SharedMutable<TypedProgram>?
}

struct TypeChecker {

  var cache: Cache

  // ...

  mutating func someProperty(d: AnyDeclID) -> T {
    if let t = local.someMap[d] {
      return t
    } else if let t = shared?[].someMap[d] {
      local.someMap[d] = t
      return t
    }

    let t = computeSomeProperty(d)

    local.someMap[d] = t
    shared?.modify { (p) in
      p.someMap[d].updateMonotonically(t)
    }
    return t
  }

}
```
We're actually batching write backs to the shared program instance, but that doesn't change the general pattern. At each call to `someProperty(_:)` we have to assume that we can get into a critical section once to read `someMap` and a second time to update it. No update occurs outside of these critical sections. `updateMonotonically` traps if the update is not monotonic, ruling out logical races (but those should not be able to trigger UB anyway, I think).

We have to make the value we read from `shared` escape at the top of the function so that we can copy it to `local` and we can't encapsulate `computeSomeProperty` in a `read` method because it may try to re-enter a critical section. `T` can be any type, including a CoW type.

Note that we're never using the `set` variant of the subscript.

**Comment by kyouko-taiga** [comment]
The fact that the problem only occurs on macOS in debug mode is suspicious, to the point I'm even starting to think that there might be a bug in `Dispatch` 😅.

I have disabled parallel type checking only on macOS-debug so that we can have a functioning CI and see whether the bug eventually impacts other configurations as we move forward (see https://github.com/hylo-lang/hylo/pull/1161).

**Comment by dabrahams** [comment]
This is entirely explained by the presence of `___chkstk_darwin` at the top of the stack trace: the type checker is blowing the stack, and the stacks allotted to dispatch queues are smaller than the main thread gets.

<img width="234" alt="image" src="https://github.com/hylo-lang/hylo/assets/44065/fb7ee25b-159a-47f2-bb98-7136500b8c0e">

**Comment by dabrahams** [comment]
The problem could be addressed by breaking type checking up into smaller tasks with their dependencies recorded, for which `OperationQueue` is well-suited, or by using `async`/`await` everywhere, or by using continuation-passing style, any of which _could_ turn out to be a performance improvement as well.

(As long as you're _not_ taking advantage of `OperationQueue`'s special capabilities, probably something like [this](https://gist.github.com/dabrahams/ea5495b4cccc2970cd56e8cfc72ca761#file-concurrentmap-swift-L38-L64) would be more efficient… but by itself I doubt it solves the blowing-the-stack problem)

**Comment by kyouko-taiga** [comment]
Great work! And those are very interesting leads for improvements.

Refactoring the type checker is no small work. That is certainly the most sophisticated part of the compiler at the moment. While the big picture is pretty easy to understand, the implementation details are a true nightmare to get right. We'll need to think about the design of the while thing very carefully.
