### ISSUE TITLE
Implement a way to skip test cases

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#1191]
Sometimes, one's work on a feature may cause some tests to crash the compiler. In those cases, it could be helpful to skip specific generated test cases, either via an option in the command line or "manually" by editing the test case themselves. That way, one could still run the part of test suite that does not cause compiler crashes.

**Comment by dabrahams** [comment]
I don't think there's anything to implement. Swift test has a filter parameter (and a negative variant). You can just edit xxx into the names of the crashers and filter them out.

**Comment by kyouko-taiga** [comment]
Nice!
