### ISSUE TITLE
Fatal error: infinite recursion

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1221]
Report a diagnostic instead please
```
public trait X {

  type Y: Regular
  fun f() -> Y


}

public trait Z: X {

  type Z: X

}

type A<B: Z> {

  typealias Z = B.Z
  typealias Y = Z.Y

  var c: Y

  fun f() -> Y { c.f() }

}
```

Yields:

/Users/dave/src/hylo/Sources/FrontEnd/TypeChecking/TypeChecker.swift:1820: Fatal error: infinite recursion

With HEAD at 3e6b3f8b

**Comment by kyouko-taiga** [comment]
There's a line attached to the fatal error. It would be good to report it, along with the hash of the commit on which the issue was observed.
