### ISSUE TITLE
Bad diagnostic

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1224]
```
public trait CollectionCore {}

public trait Collection: CollectionCore {

  type SliceCore: CollectionCore
  subscript slice(_ start: Int, _ end: Int): SliceCore { let }

}

extension Collection {

  subscript(_ start: Int, _ end: Int): SliceCore {
    yield Slice<Self>(core: self.slice[start, end]) // <=== Actual problem is here.
  }
}

type Slice<Base: Collection> {

  var core: SliceCore

  memberwise init

  typealias SliceCore = Base.SliceCore // error: type 'Base' has no member 'SliceCore'
}
```

**Comment by kyouko-taiga** [comment]
@dabrahams would you have a suggestion? Otherwise please assign this to issue to yourself, since it is not very actionable.

**Comment by dabrahams** [comment]
Report a problem on the indicated line instead of telling me my type doesn't have a member that it clearly does have?

**Comment by kyouko-taiga** [comment]
Then it's not a bad diagnostic problem. The problem in your extension is preventing name resolution to do its job. It's a bug.

**Comment by dabrahams** [comment]
It's a bug that results in a bad diagnostic; I'm not in a position to root-cause these things, but if you want to change the title of the issue to describe the problem better, please do.

**Comment by peter-evans** [comment]
This bug seems fixed. When I compile it now it points to the line that @dabrahams commented with "Actual problem is here."

```
Examples/test2.hylo:13.11-52: error: incompatible types 'Self.SliceCore' and 'Slice<Self>'
    yield Slice<Self>(core: self.slice[start, end]) // <=== Actual problem is here.
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I think this issue can be closed.

**Comment by kyouko-taiga** [comment]
It seems fixed indeed (though one will have to add appropriate access modifiers to now that they are enforced).
I can't really tell what @dabrahams was expecting so he should be the one telling whether we have to keep this issue open or not.

**Comment by dabrahams** [comment]
I was expecting the message that "Base has no member SliceCore" to not be reported on the 2nd to last line and for a diagnostic to be reported on the line with the arrow.  If both those expectations are now met, you can close it.
