### ISSUE TITLE
Broken name lookup

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1229]
This should type-check

```
public trait B {

  type C

}

public trait A: B {

  type D: B

}

type Slice<T: A> {

  typealias E = T.D.C // error: type 'Self.D' has no member 'C'

}
```

Note that there is no `Self.D`; `T != Self` in this case.

**Comment by kyouko-taiga** [comment]
Very likely related to https://github.com/hylo-lang/hylo/issues/1111

`Self.D` is very misleading but it denotes the associated type of `A`, with `Self` being the implicit generic parameter of the trait. We should find a way to print a better name in diagnostics.
