### ISSUE TITLE
Fatal error in `Emitter.emitMove` in example with conformances

### ISSUE THREAD

**Issue by lucteo** [hylo-lang/hylo#1236]
Please see example:
```
public type LocalFuture<R> {

  let r: R

  public fun await() -> R {
    r
  }
}

```

Compiling this will yield an error:
```
IR/Emitter.swift:2661: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

This comes from `emitMove` function at the following portion of the code:
```
    // Other types must be movable.
    let movable = program.conformance(
      of: t, to: program.ast.core.movable.type, exposedTo: insertionScope!)!
```

NOTE: for my longer-term type, I don't want it to be movable.

(adding `.copy()` when returning `r` makes the crash go away)

**Comment by dabrahams** [comment]
You can't return r from inside `LocalFuture` without moving it.  The fact that you haven't declared it movable is a likely cause (and I think we're going to be making that move explicit in the future).  The future should not be returning its result anyway, but projecting it, so consider a subscript.  It's in the nature of a future that it will store its result one way or the other.
