### ISSUE TITLE
Various failed attempts to form pointer to uninitialized variable

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1239]
/cc @lucteo 

Examples are shown below with the various failures.  Surely one of these should work?

I test with `swift run hc --import-builtin x.hylo -o /tmp/x && /tmp/x`

I have 8bc61e0bc checked out.

```
/*
public subscript mutable_pointer_for_initialization<T>(to
  x: // x.hylo:8.59-60: error: missing return in function expected to return 'PointerToMutable<T>'
  set T
): PointerToMutable<T> {
  set { yield PointerToMutable(base: Builtin.address(of: x)) }
}
 */

/*
public fun initialize<T, E, R>(_
  x: // x.hylo:8.59-60: error: missing return in function expected to return 'PointerToMutable<T>'
  set T, _ initializer: [E](PointerToMutable<T>)->R
) -> R {
  return initializer(PointerToMutable(base: Builtin.address(of: x)))
}
*/

/*
 // IR/Emitter.swift:1233: Fatal error: Unexpectedly found nil while unwrapping an Optional value
public subscript mutable_pointer_for_initialization<T>(to x: set T): PointerToMutable<T> {
  return PointerToMutable(base: Builtin.address(of: x))
}
 */

/*
public typealias Initializer<T, E, R> = [E](PointerToMutable<T>)->R

public fun initialize<T, E, R>(_ x: set T, _ initializer: Initializer<T,E,R>) -> R {
  // x.hylo:19.10-21: error: cannot call value of type 'Initializer<T, E, R>' as a function
  return initializer(PointerToMutable(base: Builtin.address(of: x)))
}
 */

/*
public typealias Initializer<T, E, R> = [E](PointerToMutable<T>) inout->R

public fun initialize<T, E, R>(_ x: set T, _ initializer: inout Initializer<T,E,R>) -> R {
  // x.hylo:23.10-22: error: cannot call value of type 'Initializer<T, E, R>' as a function
  return &initializer(PointerToMutable(base: Builtin.address(of: x)))
}
*/
```

**Comment by dabrahams** [comment]
…and now I realize why neither of the two basic approaches can work.  A `set` subscript would need to project an uninitialized pointer (not pointer-to-uninitialized) and would expect it to get intialized by the calling code.  In a function,we can form the pointer to the uninitialized `set` parameter but we can never convince the compiler that we've initialized `set` parameter except by, well, intializing (assigning into) it.

I'm back to thinking our type system can't support this without some new unsafe primitive, and I'm not about to advocate for that.  IMO the key enabling feature here is the one that lets  us write the implementation of a declared Hylo function in C (not the `@ffi` feature).  Once we can do that, I bet it's possible to provide some hylo facility in the standard library that doesn't force the user to write any C code, should we want to, but I'm also not claiming we want to do that.

**Comment by dabrahams** [comment]
Leaving this open because there is still one compiler trap, which should never happen, and at a minimum the error messages for the other cases are poor.

**Comment by kyouko-taiga** [comment]
>  but we can never convince the compiler that we've initialized `set` parameter

The IR has this privilege:

```
fun foo(set Int) -> {} {
b0(%0 : &Int, %1 : %{}):
  mark_state initialized %0
  mark_state initialized %1
  return
}
```

The additional unsafe primitive you're not about to advocate for is to surface `mark_state` as a function `Builtin.make_state(of:initialized:)`.

> Once we can do that, I bet it's possible to provide some hylo facility in the standard library that doesn't force the user to write any C code, should we want to, but I'm also not claiming we want to do that.

I agree that it's a reasonable thing we may want to do in the future. More generally, I think one day we'll want the ability to write IR directly. If we do that, then the question of which instruction gets surfaced as a built-in function will disappear.
