### ISSUE TITLE
Checking mutability of global bindings

### ISSUE THREAD

**Issue by tothambrus11** [hylo-lang/hylo#1445]
The compiler doesn't seem to take into account the immutability of global let bindings, so the following program compiles and runs happily:
```
let counter: Int = 0 // should be an immutable variable initialized to 0

public fun myMethod() {
  &counter += 1; // also compiles without the &
  print(counter.copy())
}

public fun main() {
  myMethod() // prints 1
  myMethod() // prints 2
  myMethod() // prints 3
}
```
This makes it possible to introduce sneaky side-effects through global variables.

**Comment by Metalymph** [comment]
About the `&` mark, I think it's a chosen style, indeed in the Stdlib every infix operator is defined in that way. However changing it is easy in the Emitter. 
About the global state , I have checked and is effectively declared as immutable in the data segment, but for some reason it escapes the exclusivity law check I still didn't figure out why.

**Comment by kyouko-taiga** [comment]
It's not about exclusivity but immutability. The program shows a compiler bug. Global bindings are immutable.
