### ISSUE TITLE
Compiler error when return type is tuple in trait

### ISSUE THREAD

**Issue by E-vyatar** [hylo-lang/hylo#1483]
trait Generator {
  type Element: Copyable
  fun next() -> (element: Element, done: Bool) <-- error: expected type but expression denotes a value
}

What worked was
trait Generator {
  type Element: Copyable
  fun next() -> Element
}

**Comment by kyouko-taiga** [comment]
The compiler is correct. That is the value syntax for tuples. The type syntax uses braces: `{element: Element, done: Bool}`
