### ISSUE TITLE
Synthesized SourceFile creation doesn't respect value semantics

### ISSUE THREAD

**Issue by tothambrus11** [hylo-lang/hylo#1489]
When creating two SourceFile objects with the same file name, the second one does not get an independent storage from the first one. This was confusing because the next time we initialize a source file, it might have a completely different content at the same file name / url as the old one.

I encountered an issue while writing tests for something that involved creating source files with specific names, and I reduced the problem to the following:

```swift
  func testUsingSourceFileWithSameName() {
    let source1 = SourceFile(synthesizedText: "type A{}", named: "example.hylo")
    XCTAssertEqual(source1.text, "type A{}")

    let source2 = SourceFile(synthesizedText: "type B{}", named: "example.hylo")
    XCTAssertEqual(source2.text, "type B{}") // XCTAssertEqual failed: ("type A{}") is not equal to ("type B{}") - 
  }
```

The problem persists even if we are working within different test cases, which is particularly spooky and breaks value semantics.
```swift
  func test1UsingSourceFileWithSameName() {
    let source = SourceFile(synthesizedText: "type A{}", named: "example.hylo")
    XCTAssertEqual(source.text, "type A{}")
  }
  func test2UsingSourceFileWithSameName() {
    let source = SourceFile(synthesizedText: "type B{}", named: "example.hylo")
    XCTAssertEqual(source.text, "type B{}") // XCTAssertEqual failed: ("type A{}") is not equal to ("type B{}") - 
  }
```

What were the design decisions behind creating a shared storage of source files? Is this a bug or intended behaviour? Can we maybe make this issue less likely to happen, e.g. only making a shared storage when the contents of the two source files equal?

**Comment by kyouko-taiga** [comment]
It is intended behavior. The purpose of the shared storage is to avoid duplicating source contents while deserializing an AST loaded from disk.

Clearly the name of the file should be unique and your code is not upholding this requirement. There's no reason to give explicit names to synthetic files, though. If you look at the constructor you'll see that the default argument is a random UUID.

**Comment by dabrahams** [comment]
@tothambrus11 unless you have some objection we haven't considere, please close the issue.  Thanks.

**Comment by tothambrus11** [comment]
Solved in https://github.com/hylo-lang/hylo/pull/1530 by removing the unnecessary parameter, so now the API is impossible to use wrong.
