### ISSUE TITLE
Invalid detection of trivially deinitializable types

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1500]
on the requirements-machine branch,

```
type X: Deinitializable {
  public var a: Int
  public memberwise init
  public fun deinit() sink { print("mort") }
}

fun eat(_ x: sink X) {
//  x.deinit()
}

public fun main() {
  let y = X(a: 0)
  eat(y)
}
```

This prints nothing.  I thought that `deinit()` would be called implicitly on an unconsumed `sink` parameter, but clearly is not.  I think it _should_ be called implicitly, but if you don't do that we have to force the user to explicitly consume all `sink` parameters.

**Comment by kyouko-taiga** [comment]
It is called implicitly but then the compiler incorrectly concludes that `X`'s deinitializer is trivial. The same bug occurs in #1499.
