### ISSUE TITLE
Mutation through let binding (and no &)?

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1523]
### Discussed in https://github.com/orgs/hylo-lang/discussions/1522

<div type='discussions-op-text'>

<sup>Originally posted by **dholmin** July 12, 2024</sup>
Hi all,

I just started out playing with the compiler (on MacOS), and one of the first things I typed that I didn't expect to compile, did. Here is the code:

```
type Thing : Deinitializable {
  public let position: Int
  public let speed: Int
  public memberwise init
}

fun update_physics(_ t: Thing)
{
  t.position += t.speed
}

public fun main()
{
  let t = Thing(position: 0, speed: 1)
  update_physics(t)
  update_physics(t)
  print(t.position)
}
```

This compiles and prints 2. I was expecting it to complain about mutation through a let binding and missing &s and maybe other things. What am I missing here?
</div>

**Comment by dholmin** [comment]
If it helps, I built Hylo from this commit: f6ee33caaf9c96f8c03aa79d2e8381debdc6dd5a
