### ISSUE TITLE
IllegalTypealias test has weird syntax

### ISSUE THREAD

**Issue by natsukagami** [hylo-lang/hylo#1529]
https://github.com/hylo-lang/hylo/blob/6476490738421da1007c6ad7d577db1fc5748edb/Tests/HyloTests/TestCases/Parsing/IllegalTypealias.hylo#L3-L4

I don't see `typealias X: Y` defined in the specs or used anywhere else in Hylo source code. Is it intended as a failure for the parser here?

**Comment by kyouko-taiga** [comment]
No, type aliases are a feature. You should find some in the standard library, in conformance declarations. For example: https://github.com/hylo-lang/hylo/blob/6476490738421da1007c6ad7d577db1fc5748edb/StandardLibrary/Sources/Core/Numbers/Integers/Int.hylo#L144

If it's missing from the spec it would be nice if you could open an issue about it.

**Comment by kyouko-taiga** [comment]
Yes, it's a parser failure.
