### ISSUE TITLE
Cannot use type aliases while trying to make a trait conform to another trait.

### ISSUE THREAD

**Issue by lucteo** [hylo-lang/hylo#1606]
For the following code:
```
trait A {}

trait B {
  type Storage
  fun f() -> Storage
}

extension A {
  public typealias Storage = Int
  public fun f() -> Storage {
    0
  }
}

public conformance A: B {}
```

I get the following error:
```
Bug.hylo:16.23-24: error: type 'Self' does not conform to trait 'B'
public conformance A: B {}
                      ^
Bug.hylo:16.23-24: note: trait 'B' requires function 'f' with type '[{self: remote let Self}] () let -> Self.Storage'
public conformance A: B {}
```

This prevents writing some generic conformance code.

Potential workarounds that work (but they don't apply for the original problem I was trying to solve):
- make `f()` in `B` and in the extension return a concrete type (e.g., `Int`)
- transform `A` into a type, and make `f()` in the extension return a concrete type (e.g., `Int`)

**Comment by kyouko-taiga** [comment]
Hmm, it seems you're writing something that is not meant to be supported by the current implementation. Specifically you can't make a trait conform to another trait.

In the near future we'll be able to write this:
```
extension<T: A> T {
  public typealias Storage = Int
  public fun f() -> Storage { 0 }
}
conformance<T: A> T: B {}
```
