### ISSUE TITLE
Poor encapsulation in the area of [`Typed`|`Scoped`]?`Program`

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#221]
It's disconcerting that all the stored properties of `TypedProgram`, which seem notionally non-public are public.  My sense is that half of them are public so the generic algorithms (which probably _are_ notionally public) implemented by `Program` extensions can use them, and the other half are public so they can be used by things like `TypedNode` and `DeclLocator`, which vend the _“actual”_ public APIs in some sense.  I don't know what the solution should be; maybe we need an additional module boundary or something. Maybe part of it could be handled by using `fileprivate` and putting all or part of `TypedNode` in the same file as `TypedProgram`. This is clearly, in part, an expressivity limitation of Swift, which we should find a way to avoid in Val.  Submodules?

/cc @lucteo @kyouko-taiga

**Comment by kyouko-taiga** [comment]
I disagree with your estimation. To me, all properties of a typed programs should be public. I suspect it's because I do not think `TypedNode` _has_ to be the only API to access the notional value of a node.

**Comment by dabrahams** [comment]
Nothing *has* to be the only API to access anything, in the long run.  The problem with not keeping access as restricted as possible _for the current state of the program_  is that refactors become much harder later.  It's exactly the same dynamic as your “reference hubs,” in fact: it's hard to keep track of which things actually use an API, and there's no disincentive for any new piece of code to reach out and touch it, so they do, and everything becomes more coupled, rather than directing access through more disciplined channels.

This is coming up now as I do the driver work, because I _do_ need to assess how things are put together.

**Comment by dabrahams** [comment]
I think we've probably addressed this.  In any event, the point was made.
