### ISSUE TITLE
Windows CI still flaky (again)

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#252]
https://github.com/val-lang/val/actions/runs/3990232735/attempts/1

**Comment by compnerd** [comment]
I was unable to reproduce this locally over 25 runs.  I wonder if there is some sort of parallelism issue here.

**Comment by C-BJ** [comment]
I think this Issue may be closed

**Comment by C-BJ** [comment]
@kyouko-taiga

**Comment by kyouko-taiga** [comment]
Fingers crossed

**Comment by kyouko-taiga** [comment]
Seems Windows CI is still flaky :(

**Comment by kyouko-taiga** [comment]
Seems I can't get a link to the failed CI jobs I re-ran. I'll post a link here next time there's a Windows failure.

**Comment by C-BJ** [comment]
![image](https://user-images.githubusercontent.com/62678643/221355064-b75fc5c5-8dd1-4712-af75-4e32e5c03174.png)
@kyouko-taiga

**Comment by kyouko-taiga** [comment]
I've been looking at that history but couldn't find the failure. I don't remember exactly which branch it was, I commit a lot of stuff these days.

The failure is about 3 days ago, feel free to look for yourself.

**Comment by C-BJ** [comment]
https://github.com/val-lang/val/actions/runs/4242066814/jobs/7373093947
Got it @kyouko-taiga

**Comment by kyouko-taiga** [comment]
Here's another one: https://github.com/val-lang/val/actions/runs/4272221910/attempts/1

**Comment by C-BJ** [comment]
https://github.com/val-lang/val/actions/runs/4335819972/jobs/7570671734

https://github.com/val-lang/val/actions/runs/4335676491/jobs/7570429339

**Comment by kyouko-taiga** [comment]
Sadly, the flakiness is getting worse and starts seriously impeding development. So I decided to disable Windows CI until we can figure out a solution (see https://github.com/val-lang/val/pull/495).

**Comment by C-BJ** [comment]
I noticed that the things happens when using Swift locally same as CI.
Swift also crashes locally.
@kyouko-taiga

**Comment by C-BJ** [comment]
I'm thinking this isn't a problem we can solve either, so what should we do?

**Comment by C-BJ** [comment]
I have an idea

**Comment by C-BJ** [comment]
Assign this issue to me?

**Comment by compnerd** [comment]
@C-BJ would you be able to get a stack trace or minidump from the failure?  That would help understand what is going on (hitting an assert/invalid memory access).

**Comment by C-BJ** [comment]
@compnerd how? I just run a Swift command and it doesn't respond, and then it exits

**Comment by C-BJ** [comment]
#517 Need to be solved first

**Comment by compnerd** [comment]
> @compnerd how? I just run a Swift command and it doesn't respond, and then it exits

If it crashes, you should be able to enable user mode dumps and collect a minidump.  There are details on how to configure that at https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps.

**Comment by kyouko-taiga** [comment]
Is this thread relevant to our issue: https://github.com/orgs/community/discussions/26933

**Comment by C-BJ** [comment]
Test fails on Windows
```
error: couldn't build D:\a\val\val\.build\x86_64-unknown-windows-msvc\release\ValTests.build\ASTTests.swift.o 
because of missing inputs: D:\a\val\val\.build\plugins\outputs\val\ValTests\TestGeneratorPlugin\ValFileTests.swift
```

Maybe it has something to do with [this](https://github.com/apple/swift-package-manager/issues/6595) SPM bug.

**Comment by C-BJ** [comment]
At this stage we have temporarily solved this problem by retrying.

**Comment by dabrahams** [comment]
I've recently reworked the CI quite substantially and uncovered/suppressed [one possible cause](https://github.com/apple/swift/issues/72121) of this problem so I'm going to close this issue until such a time as we see problems again.  At that point we should file a new issue.

**Comment by dabrahams** [comment]
Well no, that wasn't the problem.  Reopening until I implement the "try again" workaround.
This isn't a Hylo problem.

**Comment by dabrahams** [comment]
I implemented a lot of workarounds, and now we're all green again… for now.  I only pray this is an SPM problem that will be fixed by using cmake.
