### ISSUE TITLE
Fatal error: not implemented

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#670]
compile with `--import-builtin`

```
public trait Regular: Deinitializable, Copyable, Movable {}

type Pointer: Regular {

  var value: Builtin.ptr

  memberwise init

}
```

**Comment by kyouko-taiga** [comment]
There are a lot of `fatalError("not implemented")`. Those are like TODOs in the code, so I am not sure it is worth reporting all of them as issues. They have to eventually be implemented.

If you want to report them anyway, could you add from where the error originated?

**Comment by kyouko-taiga** [comment]
Can't reproduce on `main`. What's the contents of your `Regular` trait?

**Comment by dabrahams** [comment]
See the updated code snippet

**Comment by kyouko-taiga** [comment]
FWIW, I think this trait should be called `Linear`. Stepanov's `Regular` also refines `Equatable` and `Comparable`.

**Comment by dabrahams** [comment]
Good point but I just forgot to include thoseSent from my iPhoneOn Jun 20, 2023, at 12:14 AM, Dimi Racordon ***@***.***> wrote:﻿
FWIW, I think this trait should be called Linear. Stepanov's Regular also refines Equatable and Comparable.

**Comment by peter-evans** [comment]
I tried to reproduce the error and got the following.
```
.build/release/hc --import-builtin -o test Examples/test.hylo
Examples/test.hylo:3.15-22: error: type 'Pointer' does not conform to trait 'Copyable'
type Pointer: Regular {
              ~~~~~~~
Examples/test.hylo:3.15-22: note: trait 'Copyable' requires function 'copy' with type '[{self: remote let Pointer}] () let -> Pointer'
type Pointer: Regular {
              ~~~~~~~
```
I then added a `copy` function.
```
public trait Regular: Deinitializable, Copyable, Movable {}

type Pointer: Regular {

  var value: Builtin.ptr

  memberwise init

  public fun copy() -> Self {
    Pointer(value: value)
  }
}
```
Compiling throws this error:
```
.build/release/hc --import-builtin -o test Examples/test.hylo
Unexpected error

Error: Process.NonzeroExit (status: 1)
Command line: "/usr/bin/clang++" "-o" "/workspaces/hylo/test" "/tmp/A05E0A4F-0726-4904-883F-2CF8E04DC423/test.o" "/tmp/A05E0A4F-0726-4904-883F-2CF8E04DC423/Hylo.o"

  standard output:
  -------------

  -------------

  standard error:
  -------------
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

Perhaps the original issue is gone, but some other error is thrown?

**Comment by peter-evans** [comment]
Ah, if I add `public fun main() {}` it compiles fine. Perhaps the original `not implemented` error is gone and this can be closed.

**Comment by kyouko-taiga** [comment]
The error was due to the compiler not synthesizing conformances, IIRC. Now we only miss the synthetic copy, but at least the compiler doesn't crash anymore. So yes, I guess the issue's been fixed. Thanks for checking!
