### ISSUE TITLE
Poor diagnostic of overloading

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#698]
Compile this:
```swift
public fun main() {
  var x: Bool = Int() 
}
```

The compiler complains about an ambiguous use of `Int.init` rather than `Int` being incompatible with `Bool`. The problem is due to the fact that no overload candidate can make the whole statement type check, causing the type checker to conclude all choices are equally bad,

**Comment by peter-evans** [comment]
Tested on the latest compiler.

```
.build/release/hc -o test Examples/test.hylo
Examples/test.hylo:2.17-22: error: cannot initialize object of type 'Bool' with value of type 'Int'
  var x: Bool = Int() 
                ~~~~~
```
Looks like the original diagnostic message has changed to something more reasonable.

Perhaps we can close this issue.

**Comment by dabrahams** [comment]
Thanks @peter-evans !
