### ISSUE TITLE
Fix demangling of generic functions

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#791]
The demangler can't handle declarations that contain a generic parameters introduced in the same scope. For example, demangling the mangled name of the function below will crash:

```
fun f<T>(x: T) {}
```

The problem is that the symbol table is being accessed before it has been populated when the parameter type is being demangled. That's because its qualification contains the function, which is being demangled.

The solution is probably to resolve symbol lookups lazily.

**Comment by peter-evans** [comment]
Perhaps this has been fixed. With the addition of a `main()` entrypoint, the following compiles for me.

```
fun f<T>(x: T) {}

public fun main() {}
```

**Comment by kyouko-taiga** [comment]
Whether or not the program has an entry point is unrelated. The error you get when there's no `main` is currently generated by your linker and has pretty much nothing to do with `hc`.

I suppose the problem has been fixed and I just forgot to close the issue. There are many now many generic functions like `f` above that go through our mangler and our part of our test suite, like this one: https://github.com/hylo-lang/hylo/blob/08c7b539587e6885a09ecc260f8ec912f0518af9/Tests/EndToEndTests/TestCases/Monomorphize.hylo#L3
