### ISSUE TITLE
Enable testing on Windows

### ISSUE THREAD

**Issue by C-BJ** [hylo-lang/hylo#805]
We are currently blocked by:

```
error: couldn't build D:\a\val\val\.build\x86_64-unknown-windows-msvc\release\ValTests.build\ASTTests.swift.o 
because of missing inputs: D:\a\val\val\.build\plugins\outputs\val\ValTests\TestGeneratorPlugin\ValFileTests.swift
```

Maybe it has something to do with [this](https://github.com/apple/swift-package-manager/issues/6595) SPM bug.

**Comment by dabrahams** [comment]
It actually is related to [this bug](https://github.com/apple/swift-package-manager/issues/6859).
