### ISSUE TITLE
Not enough contextual information to infer generic arguments

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#819]
This should compile, but it seems the type checker fails to identify the generic arguments captured by `foo`'s receiver.
```
trait T {
  fun foo() -> Int
}

extension T {
  // error: not enough contextual information to infer generic arguments
  fun bar() -> Int { foo() }
}
```

**Comment by kyouko-taiga** [comment]
I can't reproduce the bug on `main`. The reproducer seems to pass type checking just fine.

**Comment by dabrahams** [comment]
What shall we do with issues like this?  Are you planning to go back and find the place where it stopped reproducing, and make sure that's a legit fix for the underlying problem?  I'm not saying you should, but we should have a policy about how to treat issues like this one.  "Close the issue on the assumption that it was fixed" is another possible approach, but you didn't take that one either.

**Comment by kyouko-taiga** [comment]
I didn't close the issue because I wanted to have your input on the procedure. It's nice that you bring it up.

I suspect the new type checker came was merged after this issue was reported, so in this particular case it's probably a legit fix. A variant of this test case is in our test suite, so I feel comfortable closing this issue. In general, however, I think we should adopt the policy to confirm that reported bugs have been fixed.

Perhaps we could take the habit to add a commit hash to bug reports?

**Comment by dabrahams** [comment]
Agreed, that's a good first step.  Whatever the policy is, we should [document it](https://github.com/hylo-lang/hylo/issues/968) and keep that updated.

**Comment by kyouko-taiga** [comment]
> Whatever the policy is, we should document it and keep that updated.

On it
