### ISSUE TITLE
Interacting programmatically with val compiler

### ISSUE THREAD

**Issue by RishabhRD** [hylo-lang/hylo#832]
Hi everyone, is there some way we can interact programmatically with val compiler so that we can programmatically access the low level ASTs and code structures for fun and profit?

This is very similar to haskell's ghc-lib that allow to use ghc as a library.

Thank You

**Comment by kyouko-taiga** [comment]
Yes, the compiler is designed as a library. You can look at the driver or the tests to see how different components can be assembled to parse, type check, generate IR, etc.
