### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#843]
`swift test` just got me:

```
/Users/dave/src/val/Tests/ValTests/LexerTests.swift:112: error: -[ValTests.LexerTests testFloatingPointSequences] : XCTAssertTrue failed - token has value '', not 'e'
```

I don't know how it could pass in CI, but I think @kyouko-taiga was recently in this code…?

**Comment by kyouko-taiga** [comment]
I fixed it this afternoon. Is your branch up to date with main?
