### ISSUE TITLE
Please consider adding a linking exception to the licence

### ISSUE THREAD

**Issue by tangyandfresh** [hylo-lang/hylo#890]
According to the LICENSE file, Hylo uses a bare Apache 2.0 licence, without a linking exception.

This means that if the parts of Hylo somehow end up in the binaries it produces, users may have to comply with sections 4(a), 4(b) and 4(d) of the license. This means they would have to search Hylo's source for any copyright notices and reproduce them in the documentation of their software.

That's not ideal, which is why many compilers have a linking exception in their licences (unfortunately, [not all of them](https://internals.rust-lang.org/t/does-the-standard-library-have-linking-exceptions-to-their-licensing/11377)).

Swift includes this in its license:

```
## Runtime Library Exception to the Apache 2.0 License: ##


    As an exception, if you use this Software to compile your source code and
    portions of this Software are embedded into the binary product as a result,
    you may redistribute such product without providing attribution as would
    otherwise be required by Sections 4(a), 4(b) and 4(d) of the License.
```

LLVM uses a slightly different wording:

```
As an exception, if, as a result of your compiling your source code, portions
of this Software are embedded into an Object form of such source code, you
may redistribute such embedded portions in such Object form without complying
with the conditions of Sections 4(a), 4(b) and 4(d) of the License.

```

GCC also does this, but it's a GPL project, so its waiver isn't applicable here.

As far as I can tell, Hylo doesn't have a CLA, so such a change would require the consent of the contributors. If GitHub's stats can be trusted, it seems that there are just 16 of them, so it should be doable.

**Comment by C-BJ** [comment]
AFAIK although Apache2's compatible with the GPL version 3, it's incompatible with GPLv2 - the license used by Linux, among many other projects(projects licensed to GPLv2 will not be able to use code licensed to Apache2) 

With the above changes, this problem can be solved simultaneously

BTW Rust licenses its code under both MIT and Apache2 dual licenses to also address the above issues

**Comment by kyouko-taiga** [comment]
I have close to zero experience with software licensing. So I am reluctant to make add my uniformed opinion and would prefer to get answers from most certainly more knowledgable contributors.

I'm thinking about @lucteo, @dabrahams, @camio, and @nickpdemarco in particular but obviously any contributor is welcome to weigh in.

**Comment by camio** [comment]
If a license change is in order, it might be worth changing to the Boost license which, AFAIK, doesn't have this requirement.

**Comment by lucteo** [comment]
I'm not good at reading licenses, but it felt to me that MIT license is slightly better than Boost license. With boost license, anyone can copy Hylo, remove the authors and claim it's their product; this seems unethical to me. (I don't see this as a risk, it's more like an ethical thing).

That being said, I'm happy to contribute to Hylo regardless of the license we choose.

**Comment by C-BJ** [comment]
In contrast to the MIT or Boost license Apache2 contains a patent protection clause. 
https://opensource.com/article/18/2/apache-2-patent-license

I think the best way to do this is to use the Apache2 with LLVM exception or dual licensing of MIT and Apache2.

**Comment by camio** [comment]
Choice of license depends on the purpose of the software. If betterment of society is the goal, the Boost license is good. Fewer encumbrances make for more use cases.

Ethics surrounding author recognition are not universal so I'd prefer we don't encode this POV in the license.

**Comment by dabrahams** [comment]
The exception requested here was pointed out to us by Chris Lattner when we spoke with him about licensing, and we never did anything about it.  I think it's a good idea.

As for changing licenses completely, it's a complicated calculation.  The Boost license is more appropriate than Apache 2.0 without the exception, but there are other issues to consider.  Unfortunately the Boost license (which I helped develop) hasn't seen a lot of uptake in the industry, which means it will more often require a company to do a license evaluation than if we were using a more common license, so it raises the barrier to entry.  For the record, I don't have a strong position on which license(s) we should use. 

For what it's worth, I don't have a strong position on which license(s) we should use, and I'm not at all worried about anyone claiming Hylo is their product.

**Comment by dabrahams** [comment]
Assigned to @kyouko-taiga, who said in Tuesday's meeting that she'd take responsibility for making this change.

**Comment by kyouko-taiga** [comment]
During the meeting on Tuesday 29th August, we convened that the best option is likely to adopt the same exception as the one used in Swift. Therefore I'd like to check with all contributors if they agree with that decision.

I would be grateful if the following people could answer in this thread if they agree or not:
- @dabrahams 
- @lucteo 
- @C-BJ 
- @nickpdemarco 
- @esleche 
- @WalterSmuts 
- @Zachiah 
- @jlscheerer 
- @camio 
- @compnerd 
- @codereport 
- @finestructure 
- @gsfreema 
- @MPTG94 
- @joaogui1 
- @dan-zheng

**Comment by WalterSmuts** [comment]
Agreed :+1:

**Comment by MPTG94** [comment]
Agreed 👍

**Comment by jlscheerer** [comment]
Agreed 👍

**Comment by gsfreema** [comment]
Agreed 👍

**Comment by joaogui1** [comment]
Agreed!

**Comment by finestructure** [comment]
I lack context because I merely provided configuration for the Swift Package Index listing, not any code level changes - but no objections, should agreement be required from me!

**Comment by codereport** [comment]
Fine with me

**Comment by dan-zheng** [comment]
Linking exception makes sense to me 👍

**Comment by nickpdemarco** [comment]
Approved and appreciated.

**Comment by dabrahams** [comment]
AgreedSent from my iPhoneOn Sep 1, 2023, at 1:02 AM, Dimi Racordon ***@***.***> wrote:﻿
During the meeting on Tuesday 29th August, we convened that the best option is likely to adopt the same exception as the one used in Swift. Therefore I'd like to check with all contributors if they agree with that decision.
I would be grateful if the following people could answer in this thread if they agree or not:

@dabrahams
@lucteo
@C-BJ
@nickpdemarco
@esleche
@WalterSmuts
@Zachiah
@jlscheerer
@camio
@compnerd
@codereport
@finestructure
@gsfreema
@MPTG94
@joaogui1
@dan-zheng

**Comment by compnerd** [comment]
Sure, no objections from me.

**Comment by camio** [comment]
Agreed

**Comment by kyouko-taiga** [comment]
We received agreement from most contributors. Thanks!

Unless I receive objections from @lucteo, @C-BJ, @esleche, @Zachiah, @jlscheerer, or @gsfreema by Thursday we'll move forward.

**Comment by Zachiah** [comment]
Agreed

**Comment by C-BJ** [comment]
Sorry for the delay, I'm glad to see this change
Agreed
