### ISSUE TITLE
Test Case Execution Fails Without Diagnostic for IntTests in Compiler

### ISSUE THREAD

**Issue by esleche** [hylo-lang/hylo#911]
**Descripción:**

I encountered an issue when running the IntTests test case in the compiler. The test exits with an error code but no diagnostic is provided to understand the nature of the failure.

**Steps to Reproduce:**

1. Write the given Hylo program:

`Tests/LibraryTests/TestCases/IntTests.hylo`:

```
//- compileAndRun expecting: success

fun id<T>(_ x: sink T) -> T { x }

public fun main() {
  // Int.init()
  precondition(Int() == 0)
  precondition(id<Int>(1) == 1)
}
```

2. Run the tests using the following command:

`swift test -c release --filter IntTests`

**Expected Result:**
The test case should execute successfully, or if there's an error, a diagnostic message should be provided.

**Actual Result:**
The test case exits with a signal code 4 but no diagnostic message or error explanation is provided.

```
swift test -c release --filter IntTests
Building for production...
[7/7] Compiling plugin ValidatorPlugin
Build complete! (0.66s)
Test Suite 'Selected tests' started at 2023-08-19 15:39:25.045
Test Suite 'HyloPackageTests.xctest' started at 2023-08-19 15:39:25.047
Test Suite 'Base64VarUIntTests' started at 2023-08-19 15:39:25.047
Test Case '-[ManglingTests.Base64VarUIntTests testRoundTrip]' started.
Test Case '-[ManglingTests.Base64VarUIntTests testRoundTrip]' passed (0.026 seconds).
Test Suite 'Base64VarUIntTests' passed at 2023-08-19 15:39:25.073.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.026 (0.026) seconds
Test Suite 'LibraryTests' started at 2023-08-19 15:39:25.074
Test Case '-[LibraryTests.LibraryTests test_compileAndRun_IntTests]' started.
error: Exited with signal code 4
```

**Comment by kyouko-taiga** [comment]
Thanks for reporting this bug.

It is caused by the emitter looking for `T`'s conformance to `Movable` in the body of `id`, which it can't find because `T` is a skolem. 

It will take some time to fix this. Basically we need a way to express calls to conformance requirements in generic code. I have some ideas but not any concrete plan yet.

**Comment by kyouko-taiga** [comment]
In the meantime, if you're blocked by this issue, you may replace the function by a subscript to achieve a similar effect on type inference:

```
subscript id<T: Movable>(_ x: T): T { x }

public fun main() {
  // Int.init()
  precondition(Int() == 0)
  precondition(id<Int>[1] == 1)
}
```

**Comment by peter-evans** [comment]
I can confirm that the original code, when added to `IntTests.hylo`, does now output the correct diagnostic for the bug that @kyouko-taiga describes in [this comment](https://github.com/hylo-lang/hylo/issues/911#issuecomment-1685026917).

```
$ swift test -c release --filter IntTests
Building for production...
[8/8] Compiling LibraryTests FullPathInFatalErrors.swift
Build complete! (0.61s)
Test Suite 'Selected tests' started at 2024-02-01 16:44:09.016
Test Suite 'Base64VarUIntTests' started at 2024-02-01 16:44:09.017
Test Case 'Base64VarUIntTests.testRoundTrip' started at 2024-02-01 16:44:09.017
Test Case 'Base64VarUIntTests.testRoundTrip' passed (0.015 seconds)
Test Suite 'Base64VarUIntTests' passed at 2024-02-01 16:44:09.032
         Executed 1 test, with 0 failures (0 unexpected) in 0.015 (0.015) seconds
Test Suite 'LibraryTests' started at 2024-02-01 16:44:09.032
Test Case 'LibraryTests.test_compileAndRun_IntTests' started at 2024-02-01 16:44:09.032
/workspaces/hylo/Tests/LibraryTests/TestCases/IntTests.hylo:58: error: LibraryTests.test_compileAndRun_IntTests : unexpected diagnostic: 'type 'T' does not conform to trait 'Movable''
/workspaces/hylo/Tests/LibraryTests/TestCases/IntTests.hylo:1: error: LibraryTests.test_compileAndRun_IntTests : success was expected, but processing failed with thrown error: /workspaces/hylo/Tests/LibraryTests/TestCases/IntTests.hylo:58.31-32: error: type 'T' does not conform to trait 'Movable'
Test Case 'LibraryTests.test_compileAndRun_IntTests' failed (3.257 seconds)
Test Suite 'LibraryTests' failed at 2024-02-01 16:44:12.290
         Executed 1 test, with 2 failures (0 unexpected) in 3.257 (3.257) seconds
Test Suite 'Selected tests' failed at 2024-02-01 16:44:12.290
Executed 2 tests, with 2 failures (0 unexpected) in 3.273 (3.273) seconds
```

So perhaps the title of this issue should be changed to describe the bug itself, not the lack of diagnostic.

**Comment by kyouko-taiga** [comment]
This program will compile and run as expected if it is written like this:
```swift
fun id<T: Movable>(_ x: sink T) -> T { x }

public fun main() {
  // Int.init()
  precondition(Int() == 0)
  precondition(id<Int>(1) == 1)
}
```
We had some back-and-forth in the design of the language around the relationship between `sink` and `Movable` but it is now clear that a having parameter `sink T` does not imply `T : Movable`. So compiling this program without the explicit conformance constraint reports should fail type checking, as it is now the case on main.
