### ISSUE TITLE
Shadowing not working as I'd expect

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#920]
I'd expect the definition in the local module to hide the one from the standard library.

```swift
extension Int {

  fun infix+= (_ other: Int) {
    &self = self + other
  }

}

public fun main() {
  var x = 3
  x += 1 // error: ambiguous use of 'infix+='
}
```

**Comment by kyouko-taiga** [comment]
I don't think shadowing should work here. I expect that the compiler will eventually complain about an invalid redefinition of the operator.

Extensions do not introduce another scope; they are "siblings" of the original type declaration but only visible in their introduction scopes (and their siblings). I am not sure treating extensions in other modules is worth an exception to that rule.

**Comment by dabrahams** [comment]
I think the same modularity argument applies as for shadowing of conformances.  If I extend `M.X` with something and then use that thing, it shouldn't break my code when the author of `M` adds that thing themselves.

**Comment by dabrahams** [comment]
> I thought it would be your answer but I think code breakage here is acceptable because extensions can add overloads, and these overloads will have your code break anyway.

Why I don't like overloads.  In a sense that's what I'm saying: a method local extension should (locally) shadow methods of the same name from elsewhere so we _don't_ end up with an unintentional overload set.  In fact this is why I always wanted users to be explicit about which thing they're actually overloading when they create an intentional overload.  I don't think when we gave up on the policy of "no overloads" that we ever designed the intentionality feature.

> "Obviously" overloading should apply to this case…
>
> ```
> fun f(_ x: Bool) {}
> public fun main() {
>   fun f(_ x: Int) {}
>   f(true) // OK
> }

That case is exactly the sort of thing I might expect to create a shadow unless something explicit makes it an overload.

**Comment by kyouko-taiga** [comment]
> That case is exactly the sort of thing I might expect to create a shadow unless something explicit makes it an overload.

Interesting!

Could you draw a rough picture of how you would like overloading to work ideally?

**Comment by kyouko-taiga** [comment]
@dabrahams Your original example has been "fixed".

The current definition ranking algorithm uses a definition of "depth" defined as follows:
https://github.com/hylo-lang/hylo/blob/805cacf55915a86fd701a37e68af1c511c711850/Sources/FrontEnd/TypeChecking/TypeChecker.swift#L5055-L5065

I'd like to close this issue for now. Feel free to reopen if necessary.
