### ISSUE TITLE
Avoid needless use of `Sequence.forEach`

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#930]
```swift
 batch.forEach({ check($0, ignoringSharedCache: ignoreSharedCache) })
```

Is not better to read than

```swift
 for x in batch { check(x, ignoringSharedCache: ignoreSharedCache) }
```

and produces a worse experience in the debugger.  The only thing it gets you is that there's no early termination of this loop (other than by `throw`), but that's trivially obvious.

**Comment by dabrahams** [comment]
If we can agree on this, it should go in the [conventions doc](https://github.com/hylo-lang/hylo/issues/949).

**Comment by kyouko-taiga** [comment]
Agreed
