### ISSUE TITLE
standard library typechecked only on-demand by tests?

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#938]
I have a situation where I've broken the standard library, but many tests are still passing that I expect to require it:

Test Case '-[HyloTests.HyloTests test_lowerToFinishedIR_BindingEscape]' passed (0.502 seconds).

Type-checking a module should type-check every declaration therein, right?

**Comment by kyouko-taiga** [comment]
Not necessarily. Is the standard library type checked or only the module under test. Type checking a module will only type check referenced declarations.

**Comment by dabrahams** [comment]
The test function begins with:
```swift
      var ast = AST.coreModule
      let module = try ast.makeModule(
        valSource.baseName, sourceCode: [valSource], builtinModuleAccess: true,
        diagnostics: &diagnostics)

      // Run the type checker
      let base = ScopedProgram(ast)
      let typedProgram = try TypedProgram(annotating: base, reportingDiagnosticsTo: &diagnostics)
``` 

It seems to me that if the standard library doesn't type-check, we should be getting a failure here… right?

**Comment by kyouko-taiga** [comment]
Yes it should. You pulled this code from the lowering tests, right?

I suspect the standard library did fail but extra diagnostics were not reported as error. The test mentioned in your original post is supposed to fail. It is plausible then that other diagnostics have been ignored.

One difference I can see between the code excerpt you're showing and the standard compiler driver is that we're moving to IR lowering even if an error occurred during type checking.

**Comment by kyouko-taiga** [comment]
A much simpler possibility: _where_ in the standard library is your failure? The lowering tests only load the core module.

**Comment by dabrahams** [comment]
I don't remember.  Let's close this until/unless I see it again.
