### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#970]
Compile this with 3166db52:

```
fun f<T: Movable>(src: sink T, target: set T) {
  &target = src
}
public fun main() {}
```
IR/Emitter.swift:2241: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by kyouko-taiga** [comment]
This issue has been fixed. A version of your reproducer is actually used in the standard library: https://github.com/hylo-lang/hylo/blob/92f2b6922769aa49ca0a4b7be408a4b7b19e1856/Library/Hylo/Core/PointerToMutable.hylo#L115-L120
