### ISSUE TITLE
UNIMPLEMENTED() trap for unused result

### ISSUE THREAD

**Issue by dan-tull** [hylo-lang/hylo#973]
Steps:

Compile this code with `hc` at commit 3166db52f95b333152461f1f19fbf3a77b8d7230:
```
fun z() -> String {
    return "0"
}

public fun main() {
    z();
}

```

Actual Result: 
```
$ ./.build/arm64-apple-macosx/release/hc fib-Void-NotImpl-narrow.hylo
/Users/dtull/repos/hylo/Sources/IR/Emitter.swift:956: Fatal error: not implemented
zsh: trace trap  ./.build/arm64-apple-macosx/release/hc fib-Void-NotImpl-narrow.hylo

```

Expected Result:
```
$ ./.build/arm64-apple-macosx/release/hc fib-Void-NotImpl-narrow.hylo
fib-Void-NotImpl-narrow.hylo:6.5-8: warning: unused result of type 'String'
    z();
    ~~~
```

Note this warning is emitted by simply omitting the call to `UNIMPLEMENTED` but maybe the Emitter code does need to do more for this case? At the moment, it obscures the actual mistake because the warning isn't shown.

Workaround:
Don't call functions and neglect to use the results or use `let _ = z()` in rare situations where ignoring the result is intended.

**Comment by kyouko-taiga** [comment]
Note that using `_ = z()` should be the preferred workaround, at least when the RHS is a rvalue.
