### ISSUE TITLE
`emitStore<T: NumericLiteralExpr>` should consider target word size.

### ISSUE THREAD

**Issue by nickpdemarco** [hylo-lang/hylo#994]
`Int` and `UInt` are hard-coded to be 64 bits; I think we need to consider the target platform here, perhaps by delegating to swift's `Int.bitWidth`, but I'm not sure of the semantics of that property.

**Comment by kyouko-taiga** [comment]
Related to https://github.com/hylo-lang/hylo/issues/799

We can't use `Int.bitWidth` because we probably want to be able to cross-compile.
