### ISSUE TITLE
Cannot use precondition in standard library

### ISSUE THREAD

**Issue by camio** [hylo-lang/hylo#995]
Doing so results in an illegal instruction [here](https://github.com/hylo-lang/hylo/blob/480d4aafca57c9a628c49958a84d0530b33d79bb/Sources/CodeGen/LLVM/Transpilation.swift#L184)

**Comment by dabrahams** [comment]
Can you attach the patch that reproduces this please?

Does it happen even inside an ordinary (non-generic) function?
