### ISSUE TITLE
Implement synthesization of Copyable conformances

### ISSUE THREAD

**Issue by camio** [hylo-lang/hylo#998]
```
public type Foo : Regular {
  var i : Int
  init(){ &i = 3 }
}

public conformance Foo: Equatable {
  public fun infix== (_ other: Self) -> Bool {
    return true
  }
}

// public conformance Foo: Copyable {
//   public fun copy() -> Self {
//     Foo()
//   }
// }
```

This results in `Fatal error: not implemented`. Note that when the lines are uncommented, this works okay.

**Comment by kyouko-taiga** [comment]
The problem isn't about partially implemented conformances. It is about the synthesization of `Copyable`'s conformance specifically, as it's not implemented.

**Comment by dabrahams** [comment]
Then I think you should change the issue title.

**Comment by camio** [comment]
Either way, there should be an error message instead of an illegal instruction.

**Comment by kyouko-taiga** [comment]
See also #1078

**Comment by kyouko-taiga** [comment]
This feature's been implemented.
